# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f830df21eca8fdd1625347e0553e6528"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "My Assistant Agent"
handle = "wc-agent-tooltip"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "wc-myteststore.myshopify.com"
include_config_on_deploy = true
